version: 2.1

jobs:
  build:
    docker:
      - image: debian:bullseye   
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y build-essential
            apt-get install -y gcovr lcov
      - run:
          name: Build
          command: |
            cd test
            make
      - persist_to_workspace:
          root: test
          paths:
            - out*

  test:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y build-essential
            apt-get install -y gcovr lcov
      - run:
          name: Test
          command: |
            cd test
            make
            make run
      - persist_to_workspace:
          root: test
          paths:
            - out*

  coverage:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y build-essential
            apt-get install -y gcovr lcov
      - run:
          name: Generate Coverage
          command: |
            cd test
            make
            make run 
            make coverage
      - persist_to_workspace:
          root: test
          paths:
            - coverage/html/*

workflows:
  version: 2
  build_test_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
